<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RegistrationForm extends Model
{
    use HasFactory;

    protected $table = 'events_form';
    protected $primaryKey = 'id_events_form';
    public $incrementing = true;

    protected $fillable = [
        'user_id',
        'users_role',
        'type_of_database',
        'fellows_program',
        'key_events',
        'title',
        'location',
        'start_date',
        'end_date',
        'start_time',
        'end_time',
        'time_zone',
        'logo',
        'logo_size',
        'logo_size_mobile',
        'type_event',
        'custome_link',
        'qrcode_link',
        'description',
        'subject',
        'attachment',
        'description_notif',
        'salutation',
        'salutation_required',
        'salutation_width',
        'salutation_orderby',
        'fullname',
        'fullname_required',
        'fullname_width',
        'fullname_orderby',
        'sex',
        'sex_required',
        'sex_width',
        'sex_orderby',
        'email',
        'email_required',
        'email_width',
        'email_orderby',
        'phone',
        'phone_required',
        'phone_width',
        'phone_orderby',
        'institution',
        'institution_required',
        'institution_width',
        'institution_orderby',
        'position',
        'position_required',
        'position_width',
        'position_orderby',
        'sector',
        'sector_required',
        'sector_width',
        'sector_orderby',
        'field',
        'field_required',
        'field_width',
        'field_orderby',
        'socialmedia',
        'socialmedia_required',
        'socialmedia_width',
        'socialmedia_orderby',
        'linkedin',
        'linkedin_required',
        'linkedin_width',
        'linkedin_orderby',
        'citylived',
        'citylived_required',
        'citylived_width',
        'citylived_orderby',
        'country',
        'country_required',
        'country_width',
        'country_orderby',
        'birthday',
        'birthday_required',
        'birthday_width',
        'birthday_orderby',
        'latesteducation',
        'latesteducation_required',
        'latesteducation_width',
        'latesteducation_orderby',
        'englishproficiency',
        'englishproficiency_required',
        'englishproficiency_width',
        'englishproficiency_orderby',
        'uploadfile',
        'uploadfile_required',
        'uploadfile_width',
        'uploadfile_orderby',
        'bio',
        'bio_required',
        'bio_width',
        'bio_orderby',
        'fellowship',
        'fellowship_required',
        'fellowship_width',
        'fellowship_orderby',
        'essay',
        'essay_required',
        'essay_width',
        'essay_orderby',
        'roleworkshop',
        'roleworkshop_required',
        'roleworkshop_width',
        'roleworkshop_orderby',
        'attendance',
        'attendance_required',
        'attendance_width',
        'attendance_orderby',
        'allergy',
        'allergy_required',
        'allergy_width',
        'allergy_orderby',
        'meal',
        'meal_required',
        'meal_width',
        'meal_orderby',
        'disability',
        'disability_required',
        'disability_width',
        'disability_orderby',
        'language',
        'language_required',
        'language_width',
        'language_orderby',
        'iconsent',
        'iconsent_required',
        'iconsent_width',
        'iconsent_orderby',
        'picture',
        'picture_required',
        'picture_width',
        'picture_orderby',
        'privacy',
        'privacy_required',
        'privacy_width',
        'privacy_orderby',
        'availdoc',
        'availdoc_required',
        'availdoc_width',
        'availdoc_orderby',
        'json_1',
        'json_2',
        'json_3',
        'json_4',
        'json_5',
        'json_6',
        'status',
        'condition_at',
        'updated_at',
        'created_at',
    ];

    public function fields()
    {
        return $this->hasMany(FieldEvent::class);
    }
}
